name: Project Checks
on:
  push:
    branches:
      - main
      - test-erofs
  pull_request:

jobs:
  #
  # Project checker
  #
  # based on https://github.com/containerd/project-checks/blob/main/action.yml
  project:
    name: Project Checks
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: actions/checkout@v3
        with:
          path: src/github.com/containerd/overlaybd
          fetch-depth: 100

      - name: Project checks
        uses: containerd/project-checks@v1.1.0
        with:
          working-directory: src/github.com/containerd/overlaybd
